HandyRides/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rides/', include('rides.urls')),
    path('', TemplateView.as_view(template_name="index.html"))
]

rides/urls.py
from django.urls import path

from . import views

app_name = 'rides'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create')

]

rides/models.py
from django.db import models

# Create your models here.


class Person(models.Model):
  # first_name = models.CharField(max_length=64)
  # last_name = models.CharField(max_length=64)
  # email = models.CharField(max_length=64)
  # origination_city = models.CharField(max_length=64)
  # origination_state = models.CharField(max_length=2)
  # destination_city = models.CharField(max_length=64)
  # destination_state = models.CharField(max_length=2)
  # vehicle_type = models.CharField(max_length=64)
  # premium = models.CharField(max_length=1)
  # date = models.DateField()
  # taking_passengers = models.BooleanField(default=False)
  # seats_available = models.IntegerField(default=0)


  first_name = models.CharField(max_length=64)
  X_acceleration = models.DecimalField(max_digits=64, decimal_places=64, default = 0.0)
  Y_acceleration = models.DecimalField(max_digits=64, decimal_places=64, default = 0.0)
  Z_acceleration = models.DecimalField(max_digits=64, decimal_places=64, default = 0.0)
  X_gyroscope = models.DecimalField(max_digits=64, decimal_places=64, default = 0.0)
  Y_gyroscope = models.DecimalField(max_digits=64, decimal_places=64, default = 0.0)
  Z_gyroscope = models.DecimalField(max_digits=64, decimal_places=64, default = 0.0)

rides/forms.py
from django import forms
from .models import Person
from random import randint

class RideForm(forms.Form):
    searchoc = forms.CharField(label='first_name', max_length=64, required=False)
    #searchpk = forms.IntegerField(label='pk', required=False)
    # searchdc = forms.CharField(label='Search destination city', max_length=64, required=False)

class NewRideForm(forms.ModelForm):
  class Meta:
    model = Person
    exclude = []

rides/views.py
from django.shortcuts import render, redirect

from .models import Person

# relative import of forms
from .forms import RideForm

# Create your views here.
from .forms import RideForm, NewRideForm


def index(request):

  context = {}

  if "searchoc" in request.GET:
    searchoc = request.GET["searchoc"]
    if searchoc != "":
        context["people"] = Person.objects.filter(
            origination_city__iexact=searchoc) | Person.objects.filter(origination_city__iexact=searchoc)

  if "searchos" in request.GET:
    searchos = request.GET["searchos"]
    if searchos != "":
        context["people"] = Person.objects.filter(
            origination_state__iexact=searchos) | Person.objects.filter(origination_state__iexact=searchos)

  if "searchdc" in request.GET:
    search2 = request.GET["searchdc"]
    if searchdc != "":
        context["people"] = Person.objects.filter(
            destination_city__iexact=searchdc) | Person.objects.filter(destination_city__icontains=searchdc)

  if "searchds" in request.GET:
    searchds = request.GET["searchds"]
    if searchds != "":
        context["people"] = Person.objects.filter(
            destination_state__iexact=searchds) | Person.objects.filter(destination_state__icontains=searchds)


  if "searchdate" in request.GET:
    searchdate = request.GET["searchdate"]
    if searchdate != "":
        context["people"] = Person.objects.filter(
            date__iexact=searchdate) | Person.objects.filter(date__icontains=searchdate)

  if "searchvt" in request.GET:
   searchvt = request.GET["searchvt"]
   if searchvt != "":
       context["people"] = Person.objects.filter(
           vehicle_type__iexact=searchvt) | Person.objects.filter(vehicle_type__icontains=searchvt)

  if "searchpremium" in request.GET:
    searchpremium = request.GET["searchpremium"]
    if searchpremium != "":
        context["people"] = Person.objects.filter(
            premium__iexact=searchpremium) | Person.objects.filter(premium__icontains=searchpremium)

  if "searchpass" in request.GET:
    searchpass = request.GET["searchpass"]
    if searchpass != "":
        context["people"] = Person.objects.filter(
            taking_passengers__iexact=searchvt) | Person.objects.filter(taking_passengers__icontains=searchpass)


  context["form"] = RideForm()


  return render(request, "index_view.html", context)

def create(request):
    context = {}
    context["new_ride_form"] = NewRideForm()

    if request.method == "POST":
        new_ride = NewRideForm(request.POST)
        new_ride.save()
        return redirect('/rides')
    else:
        return render(request, "find_view.html", context)

rides/templates/find_view.html
{% extends "base.html" %}

{% block content %}

<form action="{% url 'rides:create' %}" method="post">
  {% csrf_token %}
  {{ new_ride_form }}
      <input type="submit" value="Submit">
</form>

{% endblock %}

rides/templates/index_view.html
{% extends "base.html" %}

{% block content %}
<div class="main">
  <table>
      {% for person in people %}
      <tr class="{% cycle 'odd' 'even' %}">
          <td>{{ person.first_name }}</td>
          <td>{{ person.X_acceleration }}</td>
          <td>{{ person.Y_acceleration }}</td>
          <td>{{ person.Z_acceleration }}</td>
          <td>{{ person.X_gyroscope }}</td>
          <td>{{ person.Y_gyroscope }}</td>
          <td>{{ person.Z_gyroscope }}</td>

      </tr>
      {% endfor %}
  </table>
</div>


<!-- <form action="{% url 'rides:index' %}" method="get">
    {{ form }}
    <input type="submit" value="Submit" onclick="return checkForm(this.parentNode);">
</form> -->

<table>
    <tr>
        <th>name</th>
        <th>X-acceleration</th>
        <th>Y-acceleration</th>
        <th>Z-acceleration</th>
        <th>X-gyroscope</th>
        <th>Y-gyroscope</th>
        <th>Z-gyroscope</th>
        <th>Confidence</th>
    </tr>
    <tr>
        <td>Iman</td>
        <td>-1.916e-02</td>
        <td>8.627e-03</td>
        <td>-2.923e-04</td>
        <td>-3.917e-02</td>
        <td>-3.839e-04</td>
        <td>7.905e-03</td>
        <td>9.905e-01</td>
    </tr>
</table>




{% endblock %}

templates/base.html
{% load static %}

<html>
<head>
<script src="{% static 'main.js' %}"></script>
<link rel="stylesheet" href="{% static 'main.css' %}"/>
</head>
<script>
  if (getCookie('testcookie')==null) {
    window.location.href = "/";
    setCookie('testcookie', "testuser", 30);
}
</script>

<title> Fit 2 Swim </title>
  <body bgcolor="#52b5e3" text="white">
    <center>
      <h1> <p style="font-family:Impact"><font size="+5"><font color="white">Fit 2 Swim</p></h1>
      <h4> <p style="font-family:Impact"><font size="+1">Find a friend, make a splash!</p></h1>
      <img src="{% static 'fit2swim_logo.jpg' %}" alt="Image of logo" width="400" height="300">

      <br>


      {% block content %}
      {% endblock %}
      <footer>
        <br>
        <br>
        <!-- <a href="{% url 'rides:index' %}" style="font-size: medium;"> Click here to search for a swimming partner.</a>
        <br>
        {#<a href="{% url 'rides:create' %}" style="font-size: medium;"> Click here to register to find a swimming partner.</a> -->
        <br>
    </center>
  </body>
</html>

templates/index.html
{% load static %}

<html>
<head>
<script src="{% static 'main.js' %}"></script>
<link rel="stylesheet" href="{% static 'main.css' %}"/>
</head>

<title> Welcome to Fit2Swim </title>
  <body bgcolor="#52b5e3" text="black">
    <center>
      <h1p style="font-family:Impact"><font size="+5">Fit2Swim</p></h1>



      <style>
        @keyframes spinning {
          from { transform: rotate(0deg) }
          to { transform: rotate(360deg) }
        }
        .spinhov:hover {
          animation-name: spinning;
          animation-duration: 1s;
          animation-iteration-count: 1;
          /* linear | ease | ease-in | ease-out | ease-in-out */
          animation-timing-function: ease-in-out;
        }
        </style>


        <img src="{% static 'fit2swim_logo.jpg' %}" alt="Image of logo" width="400" height="300" class="spinhov"/>


      <br>
      <a href="{% url 'rides:create' %}" style="font-size: large;"> Click here to register to find a swimming partner.</a>
      <br>

      {% block content %}
      {% endblock %}

    </center>
  </body>
      <center>
      <img src="{% static 'Arrows.png' %}" alt="Image of logo" width="200" height="100">
      </center>
        <br>
        <br>
      <div id="demobox" >
        <div style="background-color: rgb(204, 208, 255) ; padding: 10px; border: 10px solid blue;">
          <h8> <p style="font-family:Impact"><font size="+3">Fit2Swim is changing how people find workout partners with the hope of creating a healthier population via swimming - one of the lowest impact forms of cardio. The platform finds individuals the ideal partners based on their skill level which is measured by accelerometers and gyroscopes during their normal swim.   </p></h1>
      </div>
      <br>
      <div id="demobox">
        <div style="background-color: rgb(204, 208, 255) ; padding: 10px; border: 10px solid blue;">
          <h8> <p style="font-family:Impact"><font size="+3">By using Fit2Swim’s partner finding service you will be able to get in shape with motivation and support from someone who is just like you!
 </p></h1>
      </div>
    </center>
  </body>
</html>

templates/index0.html
{% load static %}

<html>
<head>
<script src="{% static 'main.js' %}"></script>
<link rel="stylesheet" href="{% static 'main.css' %}"/>
</head>

<title> Fit 2 Swim </title>
  <body bgcolor="#52b5e3" text="black">
    <center>
      <h1p style="font-family:Impact"><font size="+5">Hitch A Ryde</p></h1>



      <style>
        @keyframes spinning {
          from { transform: rotate(0deg) }
          to { transform: rotate(360deg) }
        }
        .spinhov:hover {
          animation-name: spinning;
          animation-duration: 1s;
          animation-iteration-count: 1;
          /* linear | ease | ease-in | ease-out | ease-in-out */
          animation-timing-function: ease-in-out;
        }
        </style>


        <img src="{% static '1 pass.png' %}" alt="Image of logo" width="400" height="300" class="spinhov"/>


      <br>
      <div class="button" width="100" height="200"></div>
      <button onclick= "window.location.href= 'http://127.0.0.1:8000/rides'">
        Sign-up Here
      </button>

      {% block content %}
      {% endblock %}

    </center>
  </body>
      <center>
      <img src="{% static 'Arrows.png' %}" alt="Image of logo" width="200" height="100">
      </center>
        <br>
        <br>
      <div id="demobox">
        <div style="background-color: darkblue ; padding: 10px; border: 10px solid blue;">
          <h8> <p style="font-family:Impact"><font size="+3">Hitch A Ryde has potential to revolutionize the transportation industry and in the process greatly decrease CO2 and CO emissions which are destroying the environment. The idea is simple: allow users to casually share rides with people that are traveling between the same places at about the same time and share enough in common such that they are sufficiently comfortable. </p></h1>
      </div>
      <br>
      <div id="demobox">
        <div style="background-color: darkblue ; padding: 10px; border: 10px solid blue;">
          <h8> <p style="font-family:Impact"><font size="+3">By using this platform you will be able to see the differences between riding alone and using Hitch A Ryde in terms of: time, money, and environmental impact. Generating money by having users split the gas bill and subsequently taking a small share of this money would allow the app to function without initial cost or advertising. Join Hitch a Ryde to save money and ride with great company!
 </p></h1>
      </div>
    </center>
  </body>
</html>